version: '3'
 
services:
  wordpress:
    image: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: example_db
    depends_on:
      - mysql
    volumes:
      - ./wordpress_data:/var/www/html
 
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: example_user
      PMA_PASSWORD: example_password
    depends_on:
      - mysql
 
volumes:
  mysql_data:
 
